import os
from typing import Callable
from typing import Optional

from classes.PostBridge import PostBridge
from classes.PostBridge import PostBridgeClientError
from config import get_post_bridge_config
from status import info
from status import question
from status import success
from status import warning


def resolve_social_account_ids(
    client: PostBridge,
    configured_account_ids: list[int],
    platforms: list[str],
    interactive: bool,
    prompt_fn: Optional[Callable[[str], str]] = None,
) -> list[int]:
    """
    Resolve the social account IDs to use for a cross-post.

    Args:
        client (PostBridge): Post Bridge client instance.
        configured_account_ids (list[int]): Preconfigured account IDs.
        platforms (list[str]): Target platforms in config order.
        interactive (bool): Whether prompting is allowed.
        prompt_fn (Callable | None): Optional prompt function override for tests.

    Returns:
        account_ids (list[int]): Resolved target account IDs.
    """
    if configured_account_ids:
        return configured_account_ids

    if prompt_fn is None:
        prompt_fn = question

    accounts = client.list_social_accounts(platforms=platforms)
    accounts_by_platform = {}
    for account in accounts:
        platform = account.get("platform")
        accounts_by_platform.setdefault(platform, []).append(account)

    resolved_account_ids = []

    for platform in platforms:
        platform_accounts = accounts_by_platform.get(platform, [])

        if len(platform_accounts) == 0:
            warning(f"No connected Post Bridge accounts found for {platform}.")
            continue

        if len(platform_accounts) == 1:
            selected_account = platform_accounts[0]
            info(
                f"Using Post Bridge account for {platform}: "
                f"@{selected_account.get('username', '?')}"
            )
            resolved_account_ids.append(selected_account["id"])
            continue

        if not interactive:
            warning(
                f"Multiple Post Bridge accounts found for {platform}. "
                "Configure account_ids in config.json or run interactively."
            )
            return []

        info(f"Multiple Post Bridge accounts found for {platform}:")
        for index, account in enumerate(platform_accounts, start=1):
            info(
                f" {index}. @{account.get('username', '?')} "
                f"(ID: {account['id']})",
                False,
            )

        while True:
            choice = prompt_fn(
                f"Select the {platform} account to use (1-{len(platform_accounts)}): "
            ).strip()
            try:
                selected_index = int(choice) - 1
            except ValueError:
                warning("Invalid selection. Please enter a number.")
                continue

            if 0 <= selected_index < len(platform_accounts):
                selected_account = platform_accounts[selected_index]
                resolved_account_ids.append(selected_account["id"])
                break

            warning("Invalid selection. Please try again.")

    if resolved_account_ids:
        info(
            "Tip: Add these Post Bridge account IDs to config.json to skip prompts:"
        )
        info(f' "account_ids": {resolved_account_ids}', False)

    return resolved_account_ids


def build_platform_configurations(title: str) -> dict:
    """
    Build platform-specific post overrides for Post Bridge.

    Args:
        title (str): Video title generated by YouTube flow.

    Returns:
        platform_configurations (dict): Platform override payload.
    """
    cleaned_title = title.strip()
    if not cleaned_title:
        return {}

    return {
        "tiktok": {
            "title": cleaned_title,
        }
    }


def _publish_media_assets(
    media_paths: list[str],
    caption: str,
    interactive: bool,
    prompt_fn: Optional[Callable[[str], str]] = None,
    platforms: Optional[list[str]] = None,
    platform_configurations: Optional[dict] = None,
    processing_enabled: bool = True,
    force_publish: bool = False,
) -> Optional[bool]:
    """
    Shared Post Bridge publishing helper for image/video assets.
    """
    config = get_post_bridge_config()

    if not config["enabled"]:
        return None

    if not config["api_key"]:
        warning(
            "Post Bridge is enabled but no API key is configured. "
            "Set post_bridge.api_key or POST_BRIDGE_API_KEY."
        )
        return None

    valid_media_paths = []
    for media_path in media_paths:
        if not os.path.exists(media_path):
            warning(f"Cannot publish missing asset: {media_path}")
            return False
        valid_media_paths.append(media_path)

    if not valid_media_paths:
        warning("No media assets were provided for publishing.")
        return None

    configured_platforms = config["platforms"]
    selected_platforms = []
    for platform in platforms or configured_platforms:
        normalized_platform = str(platform).strip().lower()
        if normalized_platform in configured_platforms and normalized_platform not in selected_platforms:
            selected_platforms.append(normalized_platform)

    if not selected_platforms:
        selected_platforms = configured_platforms

    configured_account_ids = config["account_ids"]
    if not selected_platforms and not configured_account_ids:
        warning("Post Bridge is enabled but no supported platforms are configured.")
        return None

    if prompt_fn is None:
        prompt_fn = question

    if force_publish:
        should_publish = True
    elif interactive:
        should_publish = config["auto_crosspost"]
        if not should_publish:
            platform_label = ", ".join(selected_platforms) if selected_platforms else "configured Post Bridge accounts"
            response = prompt_fn(
                f"Publish this asset set to {platform_label} via Post Bridge? (Yes/No): "
            ).strip().lower()
            should_publish = response in {"y", "yes"}
    else:
        if not config["auto_crosspost"]:
            info(
                "Post Bridge is enabled, but auto_crosspost is disabled. "
                "Skipping automated publish."
            )
            return None
        should_publish = True

    if not should_publish:
        return None

    client = PostBridge(config["api_key"])

    try:
        account_ids = resolve_social_account_ids(
            client=client,
            configured_account_ids=configured_account_ids,
            platforms=selected_platforms,
            interactive=interactive,
            prompt_fn=prompt_fn,
        )
        if not account_ids:
            warning("No Post Bridge accounts were resolved. Skipping publish.")
            return None

        media_ids = [client.upload_media(media_path) for media_path in valid_media_paths]
        create_post_kwargs = {
            "caption": caption,
            "social_account_ids": account_ids,
            "media_ids": media_ids,
            "platform_configurations": platform_configurations,
        }
        if not processing_enabled:
            create_post_kwargs["processing_enabled"] = False

        result = client.create_post(**create_post_kwargs)

        success(f"Published via Post Bridge (post ID: {result.get('id', 'unknown')}).")
        for warning_message in result.get("warnings", []):
            warning(f"Post Bridge warning: {warning_message}")
        return True
    except PostBridgeClientError as exc:
        warning(f"Post Bridge publish failed: {exc}")
        return False


def maybe_crosspost_youtube_short(
    video_path: str,
    title: str,
    interactive: bool,
    prompt_fn: Optional[Callable[[str], str]] = None,
) -> Optional[bool]:
    """
    Cross-post a successfully uploaded YouTube Short via Post Bridge.

    Args:
        video_path (str): Path to generated video file.
        title (str): Generated YouTube title.
        interactive (bool): Whether prompting is allowed.
        prompt_fn (Callable | None): Optional prompt function override for tests.

    Returns:
        result (bool | None): True when posted, False when attempted and failed,
            None when skipped.
    """
    post_caption = title.strip()
    if not post_caption:
        post_caption = os.path.splitext(os.path.basename(video_path))[0]

    return _publish_media_assets(
        media_paths=[video_path],
        caption=post_caption,
        interactive=interactive,
        prompt_fn=prompt_fn,
        platform_configurations=build_platform_configurations(title),
        processing_enabled=True,
    )


def publish_cardnews_images(
    image_paths: list[str],
    caption: str,
    interactive: bool,
    platforms: Optional[list[str]] = None,
    prompt_fn: Optional[Callable[[str], str]] = None,
    force_publish: bool = False,
) -> Optional[bool]:
    """
    Publish one or more rendered card-news images through Post Bridge.
    """
    return _publish_media_assets(
        media_paths=image_paths,
        caption=caption,
        interactive=interactive,
        prompt_fn=prompt_fn,
        platforms=platforms,
        platform_configurations=None,
        processing_enabled=False,
        force_publish=force_publish,
    )
